'use strict';
const viewGuides={
 explore:{title:'Where is the ocean warmer or cooler?',text:'This map shows estimated ocean temperature at one depth on one date. Select a point to see its temperature profile from the surface to 1,000 metres.',steps:['Choose a date and depth below the surface.','Choose what to display, then select Show results.','Click a coloured map point or enter coordinates to inspect that location.'],read:'Use the colour bar to read values. Blank areas mean no supported data, not zero temperature. Model estimates are different from direct measurements.'},
 compare:{title:'What changed between two dates?',text:'Compare the same part of the ocean at the same depth on Date A and Date B. The third map shows the value on Date B minus the value on Date A.',steps:['Select Date A and Date B together below.','Choose a depth and either temperature or difference from the seasonal average.','Select Compare dates. Read the two maps first, then the change map.'],read:'For temperature, +2°C means Date B is 2°C warmer than Date A; −2°C means 2°C cooler. Date B can be earlier or later. This comparison does not measure model accuracy.'},
 section:{title:'What does the ocean look like from the side?',text:'Imagine cutting vertically through the ocean between two locations. The cross-section shows how the selected value changes along that route and down to 1,000 metres.',steps:['Choose a date and what to display.','Use the example route, or enter the latitude and longitude of start A and end B.','Select Show cross-section. Use the small map to locate the route.'],read:'Read left to right to travel from A to B. Read downward to go deeper. Colours show the selected value; blank areas have no supported data. Values between horizontal grid locations are interpolated.'},
 time:{title:'How does one location change over time?',text:'Follow the same ocean location across several dates. The upper chart shows all depths; the lower chart follows only the depth selected above.',steps:['Choose a location using the preset or coordinate boxes.','Select a start date, end date, and a depth for the lower chart.','Select Show time charts. Move across either chart to read dates.'],read:'On the upper chart, time runs left to right and depth increases downward. On the lower chart, the line shows the selected value over time. Gaps are missing dates, not zero values.'},
 validation:{title:'How close are the estimates to measured temperatures?',text:'These charts compare model estimates with independent Argo observations: measurements collected by instruments floating in the ocean. They describe the available evaluation sample.',steps:['Choose the observation date range below.','Select Check accuracy to update all results.','Start with Error by depth, then read the explanations beside each chart.'],read:'Lower temperature error generally means closer agreement. Check the number of samples too: a small sample cannot establish performance everywhere. A dash means a metric is unavailable.'},
 provenance:{title:'Where do these results come from?',text:'Review the loaded dataset, what its values mean, and the technical record of the model run. This helps you understand and reproduce the displayed results.',steps:['Read the dataset overview and definitions below.','Open the technical record for the exact published metadata.','Download the record as JSON if you need it for documentation.'],read:'Retrospective means historical dates, not a live forecast. Synthetic means generated demonstration data. Data availability and calibration depend on the loaded bundle.'}
};
const fieldGuides={temperature:'Ocean temperature is shown in °C, using potential temperature referenced to the surface. Higher values mean warmer water.',anomaly:'Difference from the seasonal average: +2°C means 2°C warmer than the model’s seasonal reference; −2°C means cooler. This alone does not establish a marine heatwave.',interval_width:'Uncertainty range: the width of a calibrated prediction interval in °C. Wider intervals mean a broader range of possible temperatures. A narrow interval alone does not prove accuracy.',input_fraction:'Available satellite inputs: the fraction of current-day input channels that are valid. 1 means all are available; 0.5 means half. This measures input availability, not model confidence.'};
function guidanceNode(tag,cls,text){const el=document.createElement(tag);el.className=cls;if(text)el.textContent=text;return el}
const guide=guidanceNode('section','view-guide');guide.setAttribute('aria-label','How to use this section');guide.innerHTML='<div class="guide-title"><span class="guide-tag">UNDERSTAND THIS VIEW</span><h2 id="guide-title"></h2><p id="guide-description"></p></div><ol id="guide-steps"></ol><p id="guide-reading" class="guide-reading"></p>';
document.querySelector('.controls').before(guide);
const sharedControls=document.querySelector('.controls');sharedControls.id='view-controls';
const fieldHelp=guidanceNode('p','field-help');fieldHelp.id='field-help';sharedControls.after(fieldHelp);
const advanced=guidanceNode('details','advanced-scale');advanced.innerHTML='<summary>Optional: adjust chart colours</summary><p>These limits change only the displayed colour scale, not the underlying data. The same limits apply to both comparison maps.</p><div class="scale-fields"></div>';
sharedControls.append(advanced);['cmin','cmax'].forEach(id=>advanced.querySelector('.scale-fields').append(document.getElementById(id).closest('.control-group')));
const resetScale=guidanceNode('button','btn-outline','Reset colours');resetScale.type='button';resetScale.onclick=()=>{const limits=ranges[$('variable').value];$('cmin').value=limits[0];$('cmax').value=limits[1];safe(render)};advanced.querySelector('.scale-fields').append(resetScale);
const dateBGroup=document.getElementById('date-b').closest('.control-group');document.getElementById('date').closest('.control-group').after(dateBGroup);
document.getElementById('compare-update').parentElement.hidden=true;
const mapOptions=guidanceNode('div','easy-options');mapOptions.innerHTML='<label for="map-view">Map display<select id="map-view"><option value="2d">2D map — easiest to read</option><option value="3d">3D value surface — drag to rotate</option></select></label><p id="map-reading">Click a coloured point to inspect it. Read the colour bar for the value at the selected depth.</p>';document.getElementById('map').before(mapOptions);
const notes={
 profile:['Temperature below this location','Read downward from the sea surface to 1,000 m. The solid line is the model estimate; the dotted line is the seasonal reference. Shading, when available, shows a calibrated uncertainty interval.'],
 'compare-a':['Date A — reference map','This is your starting comparison. Both date maps use the same depth and colour limits, so their colours can be compared directly.'],
 'compare-b':['Date B — comparison map','Compare this map with Date A. The difference map below calculates B minus A at each supported location.'],
 difference:['How to read the change map','Zero means no change. Positive values mean the selected quantity increased from A to B; negative values mean it decreased. For seasonal differences, this compares anomalies, not raw temperatures.'],
 'section-path':['1. Locate your route','The line joins your start point A and end point B. The chart below is a vertical slice along this path.'],
 section:['2. Look below the route','Horizontal axis: distance from point A in kilometres. Vertical axis: depth below the surface in metres. Colours show the selected value. Depth bands represent native model levels, not measurements at every metre.'],
 hovmoller:['1. All depths through time','Each column is a date and each row is a depth. Use the colour bar for values. Depth increases downward.'],
 series:['2. One depth through time','This line follows the depth chosen in the selection panel. Dates run left to right; height shows the selected value.'],
 errors:['How far off are the estimates?','RMSE and MAE measure error in °C: lower is better. RMSE gives more weight to large errors. Bias shows direction: positive means too warm; negative means too cold. Depth increases downward.'],
 skill:['Is the model better than a seasonal average?','A score above 0 means the model improves on the seasonal-reference baseline. 0 means equal error; below 0 means worse. A score of 1 means zero model error on the evaluated sample.'],
 scatter:['Do predictions match measurements?','Each dot pairs an observation (horizontal axis) with a prediction (vertical axis). Dots nearer the diagonal line agree more closely. Above the line means the prediction is warmer than the measurement.'],
 histogram:['Are the errors mostly warm or cold?','The horizontal axis is prediction minus observation in °C. Bars near 0 represent smaller errors. Positive errors are too warm; negative errors are too cold. Taller bars contain more plotted samples.'],
 coverage:['How often does the uncertainty interval include the observation?','0.9 means 90% of evaluated observations fall inside the published intervals. The dashed line is the 90% target. Read coverage together with interval width; coverage alone does not measure precision.'],
 width:['How wide are the uncertainty intervals?','This shows average interval width in °C at each depth. Smaller values mean narrower intervals, but they are only useful when their coverage is adequate. Missing values mean no calibrated result was published.'],
 'metrics-table':['What do the table columns mean?','N = matched samples; Floats = distinct instruments; RMSE/MAE = temperature error; Bias = warm/cold tendency; ACC = anomaly correlation; Skill = improvement over the seasonal baseline; Coverage = fraction inside intervals; Width = average interval width. Dashes indicate unavailable values.'],
 incois:['An additional independent benchmark','When published, this compares results with the INCOIS reference at matching monthly and spatial scales. An unavailable benchmark is not evidence of success or failure.']
};
for(const [id,[title,text]] of Object.entries(notes)){const el=document.getElementById(id),note=guidanceNode('div','chart-explanation');const h=guidanceNode('h3','',title),p=guidanceNode('p','',text);note.append(h,p);el.before(note)}
const coords=guidanceNode('div','easy-options location-picker');coords.innerHTML='<label for="location-preset">Choose a location<select id="location-preset"><option value="custom">Custom coordinates</option><option value="15,90" selected>Bay of Bengal · 15°N, 90°E</option><option value="15,65">Arabian Sea · 15°N, 65°E</option></select></label><p>Or enter latitude (north/south position) and longitude (east/west position).</p>';
document.querySelector('.point-controls').before(coords);
const timeCoords=guidanceNode('div','easy-options');timeCoords.innerHTML='<label for="time-place">Choose a location<select id="time-place"><option value="custom">Custom coordinates</option><option value="15,90">Bay of Bengal · 15°N, 90°E</option><option value="15,65">Arabian Sea · 15°N, 65°E</option></select></label><label for="time-lat">Latitude °N<input id="time-lat" type="number" min="5" max="30" step="0.25" value="15"></label><label for="time-lon">Longitude °E<input id="time-lon" type="number" min="45" max="105" step="0.25" value="90"></label>';
document.querySelector('.time-controls').before(timeCoords);
const route=guidanceNode('div','easy-options');route.innerHTML='<label for="route-preset">Choose a route<select id="route-preset"><option value="custom">Custom route</option><option value="12,82,18,92" selected>Across the Bay of Bengal · example route</option><option value="10,60,20,65">Across the Arabian Sea · example route</option></select></label><p>Start and end coordinates stay editable. Blank areas along a route mean no supported ocean data.</p>';document.querySelector('.transect-controls').before(route);
const summary=guidanceNode('article','card dataset-overview');summary.innerHTML='<h2>Loaded dataset at a glance</h2><dl id="dataset-facts"></dl><p>CSV is a spreadsheet-friendly table for one location. NetCDF contains the selected day’s scientific data. JSON stores the technical source record.</p>';document.getElementById('tab-provenance').prepend(summary);
const record=guidanceNode('details','technical-record');record.innerHTML='<summary>Open technical source record (JSON)</summary>';document.getElementById('manifest').before(record);record.append(document.getElementById('manifest'));
const glossary=guidanceNode('details','workspace-glossary');glossary.innerHTML='<summary>Quick glossary · understand the words used here</summary><dl><dt>Depth</dt><dd>Distance below the sea surface. 0 m is the surface; 1,000 m is one kilometre down.</dd><dt>Profile</dt><dd>Temperature at several depths at one location.</dd><dt>Argo float</dt><dd>An ocean instrument that records measurements as it moves through different depths.</dd><dt>Climatology</dt><dd>The seasonal reference used to describe what is usual for that time of year.</dd><dt>Anomaly</dt><dd>A difference from that seasonal reference.</dd><dt>Transect</dt><dd>A route across the ocean; its cross-section shows the water beneath that route.</dd><dt>Native levels</dt><dd>The depth levels the model actually provides. Joining them on a chart does not create extra measurements.</dd><dt>Retrospective</dt><dd>A reconstruction for historical dates, rather than a forecast or live feed.</dd></dl>';document.querySelector('.app-footer').before(glossary);
function updateViewGuidance(tab){
 const g=viewGuides[tab];$('guide-title').textContent=g.title;$('guide-description').textContent=g.text;$('guide-steps').replaceChildren(...g.steps.map(t=>guidanceNode('li','',t)));$('guide-reading').textContent='How to read it: '+g.read;
 sharedControls.hidden=['validation','provenance'].includes(tab);fieldHelp.hidden=sharedControls.hidden;fieldHelp.textContent=fieldGuides[$('variable').value];
 dateBGroup.hidden=tab!=='compare';$('date').closest('.control-group').hidden=tab==='time';$('depth').closest('.control-group').hidden=tab==='section';$('date').labels[0].textContent=tab==='compare'?'Date A · reference':'Date to explore';$('depth').labels[0].textContent=tab==='time'?'Depth for the lower chart':'Depth below surface';
 $('apply').textContent=({compare:'Compare dates',section:'Show cross-section',time:'Show time charts'})[tab]||'Show results';
 for(const o of $('variable').options)o.disabled=(o.value==='interval_width'&&(!caps.calibrated||tab==='compare'))||(o.value==='input_fraction'&&(!caps.has_quality||['compare','section','time'].includes(tab)));
 if($('variable').selectedOptions[0]?.disabled){$('variable').value='temperature';$('cmin').value=0;$('cmax').value=32;fieldHelp.textContent=fieldGuides.temperature}
 $('time-lat').value=$('lat').value;$('time-lon').value=$('lon').value;syncLocationPresets();
 const facts=[['Data type',caps.synthetic?'Synthetic demonstration':caps.mode==='retrospective'?'Historical reconstruction (retrospective)':caps.mode],['Available dates',`${caps.dates[0]} to ${caps.dates.at(-1)} · ${caps.dates.length} published dates`],['Depth coverage',`${caps.depths.length} model levels · ${caps.depths[0]}–${caps.depths.at(-1)} m`],['Observational checks',caps.has_pairs?'Argo evaluation pairs available':'No evaluation pairs published'],['Uncertainty intervals',caps.calibrated?'Published where calibration is supported':'Not published'],['INCOIS benchmark',caps.has_incois?'Published':'Not yet published']];
 $('dataset-facts').replaceChildren(...facts.flatMap(([a,b])=>[guidanceNode('dt','',a),guidanceNode('dd','',b)]));
 for(const id of ['start','end','val-start','val-end']){$(id).min=caps.dates[0];$(id).max=caps.dates.at(-1)}
}
function syncLocationPresets(){const v=`${Number($('lat').value)},${Number($('lon').value)}`;for(const id of ['location-preset','time-place'])$(id).value=[...$(id).options].some(o=>o.value===v)?v:'custom'}
function invalid(id){const v=Number($(id).value),isLat=id.includes('lat');return !$(id).value||isNaN(v)||v<(isLat?5:45)||v>(isLat?30:105)}
function validateViewSelection(){if(currentTab==='time'){if(!$('start').value||!$('end').value||$('start').value>$('end').value)throw Error('Choose a start date on or before the end date.');for(const [id,target] of [['time-lat','lat'],['time-lon','lon']]){if(invalid(id))throw Error('Enter a latitude from 5 to 30°N and a longitude from 45 to 105°E.');$(target).value=$(id).value}}
 if(currentTab==='validation'&&(!$('val-start').value||!$('val-end').value||$('val-start').value>$('val-end').value))throw Error('Choose a validation start date on or before the end date.');
 const ids=currentTab==='section'?['lat1','lon1','lat2','lon2']:currentTab==='explore'?['lat','lon']:[];for(const id of ids)if(invalid(id))throw Error('Enter coordinates inside the dataset: latitude 5–30°N and longitude 45–105°E.');
 fieldHelp.textContent=fieldGuides[$('variable').value];
}
